# permissions for end users to edit intents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intents-editor-role
rules:
- apiGroups:
  - otterize.com
  resources:
  - intents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otterize.com
  resources:
  - intents/status
  verbs:
  - get
