# permissions for end users to view intents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intents-viewer-role
rules:
- apiGroups:
  - otterize.com
  resources:
  - intents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - otterize.com
  resources:
  - intents/status
  verbs:
  - get
